Cresk/Models/DbTag.cs
using System.ComponentModel.DataAnnotations;

namespace Cresk.Models
{
    public class DbTag
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public DbTag()
        {
            this.Id = Guid.NewGuid().ToString();
        }
    }
}

Cresk/Controllers/DbTagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cresk.Data;
using Cresk.Models;
using Cresk.ViewModels;
using System.Net.Sockets;
using Microsoft.AspNetCore.Authorization;

namespace Cresk.Controllers
{
    [Authorize]
    public class DbTagController : Controller
    {
        private readonly CreskContext _context;

        public DbTagController(CreskContext context)
        {
            _context = context;
        }

        // GET: DbTag
        public async Task<IActionResult> Index(string searchString)
        {
            var tag = _context.DbTag.AsQueryable();
            if (!String.IsNullOrEmpty(searchString))
            {
                tag = tag.Where(t => t.Name!.Contains(searchString));
            }
            var tagFromDatabase = await tag.ToListAsync();
            var tagsListViewModel = tagFromDatabase.Select(tagFromDatabase => new IndexDbTagViewModel()
            {
                Id = tagFromDatabase.Id,
                Name = tagFromDatabase.Name,
                Description = tagFromDatabase.Description
            });

            return View(tagsListViewModel);
        }

        // GET: DbTag/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DbTag/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateDbTagViewModel vm)
        {
            DbTag dbTag = new DbTag();
            dbTag.Name = vm.Name;
            dbTag.Description = vm.Description;

            if (ModelState.IsValid)
            {
                _context.Add(dbTag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dbTag);
        }

        // GET: DbTag/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.DbTag == null)
            {
                return NotFound();
            }

            var dbTag = await _context.DbTag.FindAsync(id);
            if (dbTag == null)
            {
                return NotFound();
            }

            EditDbTagViewModel vmDbTag = new EditDbTagViewModel();
            vmDbTag.Name = dbTag.Name;
            vmDbTag.Description = dbTag.Description;
            return View(vmDbTag);
        }

        // POST: DbTag/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditDbTagViewModel vmDbTag)
        {
            var dbTag = await _context.DbTag.FindAsync(vmDbTag.Id);
            if (dbTag == null)
            {
                return View(vmDbTag);
            }
            dbTag.Name = vmDbTag.Name;
            dbTag.Description = vmDbTag.Description;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: DbTag/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.DbTag == null)
            {
                return NotFound();
            }

            var dbTag = await _context.DbTag
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dbTag == null)
            {
                return NotFound();
            }

            return View(dbTag);
        }

        // POST: DbTag/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.DbTag == null)
            {
                return Problem("Entity set 'CreskContext.DbTag'  is null.");
            }
            var dbTag = await _context.DbTag.FindAsync(id);
            if (dbTag != null)
            {
                _context.DbTag.Remove(dbTag);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DbTagExists(string id)
        {
          return _context.DbTag.Any(e => e.Id == id);
        }
    }
}

Cresk/Views/DbTag/Create.cshtml
@model Cresk.ViewModels.CreateDbTagViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-info">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cresk/Views/DbTag/Delete.cshtml
@model Cresk.Models.DbTag

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DbTag</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-info">Back to List</a>
    </form>
</div>

Cresk/Views/DbTag/Edit.cshtml
@model Cresk.ViewModels.EditDbTagViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DbTag</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-info">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cresk/Views/DbTag/Index.cshtml
@model IEnumerable<Cresk.ViewModels.IndexDbTagViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Tags list</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>

<form asp-controller="DbTag" asp-action="Index" method="get">
    <p>
        Search by name: <input type="text" name="SearchString" class="form-control" />
        <input type="submit" class="btn btn-success" value="Wyszukaj" />
    </p>
</form>
<a asp-action="Index" class="btn btn-info">Back to Full List</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="fa-solid fa-circle-info"></a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="fa-solid fa-trash"></a>
            </td>
        </tr>
}
    </tbody>
</table>