Cresk/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cresk.Data;
using Cresk.Models;
using Cresk.ViewModels;
using System.Net.Sockets;
using Microsoft.AspNetCore.Authorization;
using Cresk.ViewModels.Company;

namespace Cresk.Controllers
{
    public class CompanyController : Controller
    {
        private readonly CreskContext _context;

        public CompanyController(CreskContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string searchString)
        {
            var company = _context.Companies.AsQueryable();
            if (!String.IsNullOrEmpty(searchString))
            {
                company = company.Where(t => t.CompanyName!.Contains(searchString));
            }
            var companyFromDatabase = await company.ToListAsync();
            var companiesListViewModel = companyFromDatabase.Select(companyFromDatabase => new IndexCompanyViewModel()
            {
                Id = companyFromDatabase.Id,
                CompanyName = companyFromDatabase.CompanyName
            });

            return View(companiesListViewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        // POST: Company/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCompanyViewModel vm)
        {
            Company company = new Company();
            company.CompanyName = vm.CompanyName;

            if (ModelState.IsValid)
            {
                _context.Add(company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: DbTag/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Companies == null)
            {
                return NotFound();
            }

            var company = await _context.Companies.FindAsync(id);
            if (company == null)
            {
                return NotFound();
            }

            EditCompanyViewModel vm = new EditCompanyViewModel();
            vm.CompanyName = company.CompanyName;
            return View(vm);
        }

        // POST: DbTag/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditCompanyViewModel vm)
        {
            var company = await _context.Companies.FindAsync(vm.Id);
            if (company == null)
            {
                return View(vm);
            }
            company.CompanyName = vm.CompanyName;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: DbTag/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Companies == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: DbTag/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Companies == null)
            {
                return Problem("Entity set 'CreskContext.Companies'  is null.");
            }
            var company = await _context.Companies.FindAsync(id);
            if (company != null)
            {
                _context.Companies.Remove(company);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Cresk/Controllers/DbTicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cresk.Data;
using Cresk.Models;
using Cresk.ViewModels;
using Cresk.Enums;
using Microsoft.AspNetCore.Authorization;
using Cresk.ViewModels.Tickets;
using Cresk.ViewModels.Chat;
using Microsoft.AspNetCore.Identity;

namespace Cresk.Controllers
{
    public class DbTicketController : Controller
    {
        private readonly CreskContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public DbTicketController(CreskContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        // GET: DbTicket
        public async Task<IActionResult> Index(string searchString, TicketStatus? ticketStatus, TicketPriority? ticketPriority, string categoryId)
        {
            var ticket = _context.DbTicket.Include(i => i.Category).AsQueryable();
            
            if (!String.IsNullOrEmpty(searchString))
            {
                ticket = ticket.Where(s => s.Title.Contains(searchString));
            }

            if (ticketStatus.HasValue)
            {
                ticket = ticket.Where(t => t.Status == ticketStatus);
            }

            if (ticketPriority.HasValue)
            {
                ticket = ticket.Where(j => j.Priority == ticketPriority);
            }

            if (!string.IsNullOrWhiteSpace(categoryId))
            {
                ticket = ticket.Where(k => k.CategoryId == categoryId);
            }

            ticket = ticket.OrderByDescending(t => t.CreatedDate);
            var ticketsFromDatabase = await ticket.ToListAsync();
            var tags = await _context.TicketCategories.Select(categoryFromDatabase => new SelectListItem()
            {
                Value = categoryFromDatabase.Id,
                Text = categoryFromDatabase.Name
            }).ToListAsync();


            //var ticketListViewModel = ticketsFromDatabase.Select(ticketFromDatabase => new IndexDbTicketViewModel()
            var ticketListViewModel = ticketsFromDatabase.Where(x => x.Status != TicketStatus.Resolved)
            .Select(ticketsFromDatabase => new IndexDbTicketViewModel()
            {
                CategoryName = ticketsFromDatabase.Category!=null?ticketsFromDatabase.Category.Name:"----", 
                Description = ticketsFromDatabase.Description,
                ModifyDate = ticketsFromDatabase.ModifyData, 
                EmailAddress = ticketsFromDatabase.Email,
                TicketPriority = ticketsFromDatabase.Priority,
                TicketStatus = ticketsFromDatabase.Status,
                Id = ticketsFromDatabase.Id,
                Title = ticketsFromDatabase.Title,
                TicketDisplayNumber = ticketsFromDatabase.TicketDisplayNumber
            });

            var indexViewModel = new TicketIndexViewModel();
            indexViewModel.IndexDbTicketViewModels = ticketListViewModel.ToList();
            indexViewModel.SearchString = searchString;
            indexViewModel.TicketStatus = ticketStatus;
            indexViewModel.CategoryList= tags;

            return View(indexViewModel);
        }

        // GET: DbTicket/Create
        public async Task<IActionResult> Create()
        {
            var tags = await _context.TicketCategories.Select(categoryFromDatabase => new SelectListItem()
            {
                Value = categoryFromDatabase.Id,
                Text = categoryFromDatabase.Name
            }).ToListAsync();
            CreateDbTicketViewModel vm = new CreateDbTicketViewModel();
            vm.CategoryList = tags;
            return View(vm);
        }

        // POST: DbTicket/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateDbTicketViewModel vm)
        {

            DbTicket dbTicket = new DbTicket();
            if (!string.IsNullOrWhiteSpace(vm.CategoryId))
            {
                dbTicket.CategoryId = vm.CategoryId;
            }
            dbTicket.Title = vm.Title;
            dbTicket.Description = vm.Description;
            dbTicket.Priority = vm.Priority;
            dbTicket.Email = User.Identity.Name;
            dbTicket.CreatedDate = DateTime.Now;
            dbTicket.ModifyData = DateTime.Now;
            dbTicket.Status = TicketStatus.New;           

            _context.Add(dbTicket);
            await _context.SaveChangesAsync();

            var chat = new Chat();
            chat.DbTicketId = dbTicket.Id;
            _context.Chats.Add(chat);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: DbTicket/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.DbTicket == null)
            {
                return NotFound();
            }

            var dbTicket = await _context.DbTicket.FindAsync(id);
            if (dbTicket == null)
            {
                return NotFound();
            }
            var tags = await _context.TicketCategories.Select(categoryFromDatabase => new SelectListItem()
            {
                Value = categoryFromDatabase.Id,
                Text = categoryFromDatabase.Name
            }).ToListAsync();

            var chat = await _context.Chats.FirstOrDefaultAsync(m => m.DbTicketId == dbTicket.Id);
            var chatMessages = await _context.ChatMessages
                .Where(t => t.ChatId == chat.Id)
                .OrderByDescending(t => t.CreateTime)
                .Select(t => new ChatMessageViewModel()
                {
                    CreateTime = t.CreateTime,
                    Message = t.Message,
                    Username = t.Username
                })
                .ToListAsync();

            EditDbTicketViewModel vm = new EditDbTicketViewModel();
            vm.CategoryList = tags;
            vm.Title = dbTicket.Title;
            vm.Status = dbTicket.Status;
            vm.Priority = dbTicket.Priority;
            vm.Email = dbTicket.Email;
            vm.Description = dbTicket.Description;
            vm.CreateDate = dbTicket.CreatedDate;
            vm.ModifyDate = dbTicket.ModifyData;
            vm.ChatMessageViewModels = chatMessages;
            return View(vm);
        }

        // POST: DbTicket/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditDbTicketViewModel vm)
        {
            var dbTicket = await _context.DbTicket.FindAsync(vm.Id);
            if(dbTicket == null)
            {
                return View(vm);
            }
            if (!string.IsNullOrWhiteSpace(vm.CategoryId))
            {
                dbTicket.CategoryId = vm.CategoryId;
            }

            dbTicket.Status = vm.Status;
            dbTicket.Priority = vm.Priority;
            dbTicket.Title = vm.Title;
            dbTicket.Email = vm.Email;
            dbTicket.Description = vm.Description;
            dbTicket.ModifyData = DateTime.Now;

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> AddMessage(string message, string dbTicketId)
        {
            var chat = await _context.Chats.FirstOrDefaultAsync(m => m.DbTicketId == dbTicketId);
            var userId = _userManager.GetUserId(User);
            var chatMessage = new ChatMessage()
            {
                ChatId = chat.Id,
                CreateTime = DateTime.Now,
                Message = message,
                UserId = userId,
                Username = User.Identity.Name
            };
            await _context.ChatMessages.AddAsync(chatMessage);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Edit), new {id = dbTicketId});
        }


        // GET: DbTicket/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.DbTicket == null)
            {
                return NotFound();
            }

            var dbTicket = await _context.DbTicket
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dbTicket == null)
            {
                return NotFound();
            }

            return View(dbTicket);
        }

        // POST: DbTicket/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.DbTicket == null)
            {
                return Problem("Entity set 'CreskContext.DbTicket'  is null.");
            }
            var dbTicket = await _context.DbTicket.FindAsync(id);
            if (dbTicket != null)
            {
                _context.DbTicket.Remove(dbTicket);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Cresk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cresk</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/sidebarNavbar.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <div class="main-container">
    <div class="top_navbar">
        <div class="hamburger">
            <i class="fa-solid fa-bars"></i>
        </div>
        <div class="logo">
            <img src="~/img/name_1.png" height="65px"/>
        </div>
        <ul class="user-area">
            <form method="get" asp-controller="Account" asp-action="Logout">
                Welcome @User.Identity.Name
                <button type="submit" class="btn btn-dark">Logout</button>
            </form>
        </ul>
    </div>
    <div class="page-area">
        <div class="sidebar">
            <ul class="navigation-list">
                <li>
                    <a class="navigation-link" asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fa-solid fa-hand" aria-hidden="true"></i>
                        <span class="navigation-link-text">
                            Home
                        </span>
                    </a>
                </li>
                <li>
                    <a class="navigation-link"  asp-area="" asp-controller="DbTicket" asp-action="Index">
                        <i class="fa-solid fa-ticket" aria-hidden="true"></i>
                        <span class="navigation-link-text">
                            Tickets
                        </span>
                    </a>
                </li>
                <li>
                    <a class="navigation-link" asp-area="" asp-controller="TicketCategory" asp-action="Index">
                        <i class="fa-solid fa-tag" aria-hidden="true"></i>
                        <span class="navigation-link-text">
                            Categories
                        </span>
                    </a>
                </li>
                <li>
                    <a class="navigation-link" asp-area="" asp-controller="Company" asp-action="Index">
                        <i class="fa-solid fa-building" aria-hidden="true"></i>
                        <span class="navigation-link-text">
                            Companies
                        </span>
                    </a>
                </li>
                <li>
                    <a class="navigation-link" asp-area="" asp-controller="Home" asp-action="Privacy">
                        <i class="fa-solid fa-lock" aria-hidden="true"></i>
                        <span class="navigation-link-text">
                            Privacy
                        </span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="main-content">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
    $(document).ready(function() {
        $(".hamburger").click(function() {
            $(".sidebar").toggleClass("minimalize");
            if ($(".sidebar").hasClass("minimalize")) {
                localStorage.setItem("sidebarHidden", true)
            }
            else {
                localStorage.setItem("sidebarHidden", false)
            }
            const links = document.querySelectorAll('.navigation-link-text');
                links.forEach(link => {
                link.classList.toggle('hide');
            });
        });
    });
    const sidebarHidden = localStorage.getItem("sidebarHidden");
    if (sidebarHidden === "true") {
        $(".sidebar").toggleClass("minimalize");
        const links = document.querySelectorAll('.navigation-link-text');
            links.forEach(link => {
            link.classList.toggle('hide');
        });
    }

    $(".modal-link").click(function() {
    $('#modal').modal('show');
        });
    </script>

</body>
</html>