Cresk/Models/TicketCategory.cs
using System.ComponentModel.DataAnnotations;

namespace Cresk.Models
{
    public class TicketCategory
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public TicketCategory()
        {
            this.Id = Guid.NewGuid().ToString();
        }
    }
}

Cresk/Controllers/TicketCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cresk.Data;
using Cresk.Models;
using Cresk.ViewModels;
using System.Net.Sockets;
using Microsoft.AspNetCore.Authorization;
using Cresk.ViewModels.Category;

namespace Cresk.Controllers
{
    [Authorize]
    public class TicketCategoryController : Controller
    {
        private readonly CreskContext _context;

        public TicketCategoryController(CreskContext context)
        {
            _context = context;
        }

        // GET: DbTag
        public async Task<IActionResult> Index(string searchString)
        {
            var category = _context.TicketCategories.AsQueryable();
            if (!String.IsNullOrEmpty(searchString))
            {
                category = category.Where(t => t.Name!.Contains(searchString));
            }
            var categoriesFromDatabase = await category.ToListAsync();
            var categoriesListViewModel = categoriesFromDatabase.Select(categoryFromDatabase => new IndexCategoryViewModel()
            {
                Id = categoryFromDatabase.Id,
                Name = categoryFromDatabase.Name,
                Description = categoryFromDatabase.Description
            });

            return View(categoriesListViewModel);
        }

        // GET: DbTag/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DbTag/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCategoryViewModel vm)
        {
            TicketCategory category = new TicketCategory();
            category.Name = vm.Name;
            category.Description = vm.Description;

            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: DbTag/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.TicketCategories == null)
            {
                return NotFound();
            }

            var category = await _context.TicketCategories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            EditCategoryViewModel vm = new EditCategoryViewModel();
            vm.Name = category.Name;
            vm.Description = category.Description;
            return View(vm);
        }

        // POST: DbTag/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditCategoryViewModel vm)
        {
            var category = await _context.TicketCategories.FindAsync(vm.Id);
            if (category == null)
            {
                return View(vm);
            }
            category.Name = vm.Name;
            category.Description = vm.Description;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: DbTag/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.TicketCategories == null)
            {
                return NotFound();
            }

            var category = await _context.TicketCategories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: DbTag/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.TicketCategories == null)
            {
                return Problem("Entity set 'CreskContext.Category'  is null.");
            }
            var category = await _context.TicketCategories.FindAsync(id);
            if (category != null)
            {
                _context.TicketCategories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Cresk/Views/TicketCategory/Create.cshtml
@model Cresk.ViewModels.Category.CreateCategoryViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cresk/Views/TicketCategory/Delete.cshtml
@model Cresk.Models.TicketCategory

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DbTag</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

Cresk/Views/TicketCategory/Edit.cshtml
@model Cresk.ViewModels.Category.EditCategoryViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Cresk/Views/TicketCategory/Index.cshtml
@model IEnumerable<Cresk.ViewModels.Category.IndexCategoryViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Category list</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success">
        <i class="fa-add fa-solid"></i>
        Create New
    </a>
</p>

<form asp-controller="TicketCategory" asp-action="Index" method="get">
    <p>
        Search by name: <input type="text" name="SearchString" class="form-control" />
        <input type="submit" class="btn btn-secondary" value="Search" />
        <a asp-action="Index" class="btn btn-secondary">Back to Full List</a>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="fa-solid fa-circle-info"></a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="fa-solid fa-trash text-danger"></a>
            </td>
        </tr>
}
    </tbody>
</table>